// Package imagebuilder provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package imagebuilder

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/core/v1beta1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xd/XLcNpJ/FRT3qtbemw/byd6Htq7qFNne1caOvZKc/WOVSmHInhmsSIABwJEmKVXd",
	"Q9wT3pNcNQCSIAnOcGxJthL+Jc0QbACNRvevP4D5JYpFlgsOXKvo6JdIxWvIqPn3OGffg1RMcPyUgIol",
	"y7X5GB2/P3XPSAJLxkERvQaysd9BQiwdIpZEr5kiEnIJCrimSAC/ppyIxT8h1jNyDhJfJGotijQhseAb",
	"kJpIiMWKs58raopoYbpJqQalCeMaJKcp2dC0gAmhPCEZ3RIJSJcU3KNgmqgZeSskEMaX4oistc7V0Xy+",
	"Ynp29R9qxsQ8FllWcKa381hwLdmi0EKqeQIbSOeKraZUxmumIdaFhDnN2dQMluOk1CxLfidBiULGoGbR",
	"JAJeZNHRP6LNc5rma/o8mkTLlK3WOtYp9lZ9/8Mk0tscoqNIacn4KppEN1N8e7qhktMMFJKp1+P7mmD9",
	"5euS9Kn43iN8M12JaZP67ST6hvGE8dWF+b69uBdrIPgGLtPCNiRLIQ3rWUZXQBYFSxN/ikBluo0mEa7M",
	"wOl4Q3jl3va+emMI3U4i88w96A7VPK0GGQu+ZKtCWiGbEsgWkCgSg9RsyWKqcenraeAEcilyfAxG5PVQ",
	"fnTn3pn07e0kkvBTwSQk2Mw8rVtZ4ce1eHWTC6lfC5lRvX9BlqYd7gQw73mrokVD6rLkKppEP8Xi+kU0",
	"iZgS5adpwtQVSq6mjIMcuF7tYX7/9uW3UXf0fzt59/cXge9Pz9/1tX7J1NVJPZrbSXSK8/kGhazLjPpZ",
	"rVUUoVYmCXIcdQPKKyXVHPsWnDZ03L9IWEZH0e/mtU6cO9Uz97Th7SQy5OwCqIB2lJJucbHMWO2cSaUa",
	"iF5T/LgECTwGqyDrWc3IO55uSS7yAndTQq7XwMk102tLSJGfCpBbklNJM9A4N0W0LMzsmIZM7ZuKNyqc",
	"i1t7ioPGz1eMB9j+LeMJ9kSJFRKrUeslwK9QFM9enV9Uc7Vzs6LurVat8lFdM74EaVsupcgMFeBJLhi3",
	"0h2nDLgmqlhkTKtyidEazMgJ5VxosgBS5Amya0ZOOTmhGaQnVMG9K3xknpoiy4zK7yjaDDRNqKb71iQW",
	"En7cPF+Aps9/FDlwmrMf3xnGvQVNkZTKIR60tEaMzrE1vqWpLtQB79n2be3lbRQnId7c3NhCyq0m3KvD",
	"O00IUmNLBqpHs5fGqDJDCUOCGeNUC4k9ZDTPXWdWPffMu2FdnPnqaYoWqWx5W+mR7Xc0w1fMxG8nkeDw",
	"bhkd/WM3uxvd3k52N2503NSOJ4InTDvtRdN0QNdBQavofEMVmAGF7eIwEaqoGWs20A7+MGmJRUXFLHdD",
	"61cYK8yMM6AqBFrt95X0eCTPgCZbFDJLwDej76EUDtPU/vu+UGv734nI8hQ04H54TVlq/jmhPIbUNTD/",
	"QzLQyvZOpx5HbxNvgP1kqpH3NvGn1Nuomms/GY8Jexohd8JL2YOHHBbyVjC4dmZZP57x2I0j0RjdS1Aa",
	"VU3QMwo28zQaSl7iPfF1me6DKeZrq2lC2BAnYV0tIKLQeeER6lgk8+SCrnpgJl0NpiQhF4ppIbf7h3VW",
	"ta3BAT7ClXx3cop4Ni/Uus0Kh2l3I2tvHBOPVd5Ud1umN0zpXQuJzy30SfG/puA1PL47ApcliGsO6M2e",
	"zodjP4usR+j3BUM/XGwL/A4DYlYIdsv7GSzPzRrtEvqqkae7KHFra/emWTLKQwLZo8JKyvv1RYAm6ohC",
	"AaGK1J10uL7fha9fLu1EPbaBbvykNZ3d/N7P7A6nkQVNXrch70cbCJ/spxmIvZTu0kA4V77UNXv6vmML",
	"ce5cr971yyEm9uGiXD27lnFt5SlvRM8u+asbGut0SwQ3UzUPX8KScQeQlkRI8sTN9F991PCUZIUyqi+X",
	"YsMSSMj//c//Yr9bQiWQrNAFTdMtgZs4LRTbwOyS/30NPNQJU0SBnpQspTxpAJSyJ7pABf6nuhNcpnQD",
	"Sa26T5vECdUklkA1EM0yS1lpISEhjBPrmM4ueUeYF7WnOMyUeW5Z0sRmw973AV25ARo8GqivvKk3zaCN",
	"TeE/VEFCBJ9d8redNTJBHiM4M28tzGdvWuVK7lozXJ4EJNu9Ojzxg4d0ZWx8ocWU8VhCBhxtqlmfzs5W",
	"lUobGFWw7W8nUaFAnvje/HAiHzqvtvd5KTl7dnMVEundz6aFH180YKSQ0qAR+9QmMbzAXRcAeggiLEJ+",
	"i1KUWp5Ah/eVqxOYwokbYt2ma1A/AivWcYYAaDQjPSvDmeF5Los0dYJWBz678yVPYLaaTchPBd0iRhNy",
	"NTcPcKsdabp6GuRISpU+B+DhvvGpVUCVASXXCCIAOHmyBir1Aqg2pG10PTqKEFBO8aUgsqOcLUHpl2wF",
	"IdcBe03Ms9Acy7d7TKZVqi/vQI+VtM4/erOWFHrzgDjTyg4oyCjXLC7TgHY1yfPZs9mLpxMvot2yC9c7",
	"DVPYuu/Y3h9CGqZvp3caeyAMVdW+yGNzw+fFImXxFfTgHfuYXMG2ItTtIygW2Iz3wrvy6WFUW7qz6mLi",
	"TaNXkZ5QTVOxclmEMIMbbUjK+JWqNKZnh7QwmRoJc/fCjLzjBDYgt0QVcQxKLYv0ktud6zZUpUWSNr2J",
	"eU6VEjEz0uaonmrIUKSs5CVEyEvuHEdreCnhcF3JLnAttyF08rFe/QP41l9KAqKx8DYRcZfphAb5HcGb",
	"TrtAEKcpo58pmLNjEMMNdXNHfp7gzmMJg3QFdIAEBZy82D4vU/EdjdsUobhWRMNcdV9zoYpyxQtxqSZf",
	"wpIWqa7qYuzShV1JtiRc6B6DOinHNsjX8XV1LRLXa5AQGHaaovdYa90qWhcaRsJUntJtmD1/KTLKpxJo",
	"QhcpIizT1g5NrcU1R7eyXBLc5YyvwjKZiLjIymqkDzIN7U9+ZYssXI1R45Ug0bXIIKernnUtn5IPZ28q",
	"O10OFsUVXXlTD9Ubk7lTl9SJLO782lSikAX7d2EG2e31vXuCK2twg1rjh2Vnfj1wlyahpX4J2iSYmmwP",
	"8m1CcgMG6CLdogBkVF4lKAwWywe7VWsh9Uu/x04JB1lIBksiOExTxoF4jwfPThV5GB6V0uUaeLUhQu6V",
	"tJYmDIhGYzv3KsH6nR7t58mOMRASCmV2noYsRyRfasNmUG7ihyJsVV4JqnKqcTuZdfRiYWpGTlA/IJ0Q",
	"QJRstQKpCBcmPpFZYVhsCdMK0uVsxGiHY7Sav3cP0Gra+1OlwbY78qV1KNdIlpWiyvkpxemiHddyto+g",
	"kfoTYUbxIWsKVHs5yDsIrD/2fOmA5dwBtpuNAkg7YIkeGGb3jWA4xvZU5giwdwHslnbZJzIBaF3ZmLat",
	"aAe2mbIl6CwMug9NCIR11yeFvDd90bNzyDYgG1axFZC3gB+RDHl7/Nd3Z7O3p9+9O5vdeKG1m6ezS26i",
	"S1THa1KNiTy5eRqK6BPBCdB47cVWqoxUNInghmZ5iktqiO9VJo4tzcxLPedeCdkZOao84bq+l5eItazw",
	"1aI6KYCGwGhDwznjDiVsaQJE2sFA9ahAwlgkcZ/Qx49LHVQg6168hwpZS/mLK+dsDeuu6zm7Aa8efhxS",
	"0emIDirpPLEK5EGKOoNTalV1Bts0BrmDVLOys4dUq7Qz2KpZ2xkm1C7u3NHKr+4MCdTu8s5XVWjtDuo7",
	"A923Cjz9Ayrv17h9wpkcfGQywEQxvkqhPJdjTZJqDfSnAgrD0dhfy7xasditSzSJlpb5B0/KG/Lfyt7C",
	"j/vkyWsSlKUGiWq84QZOhFps3eE+7AzSf97o/KeF5cdzNr/ZYksHF3ZV//lNhpT/WQy878iLV8+4102p",
	"i0E/9VBLkOYPIWZcDKzRbHlE9eSHFG7uU5j1ULya6PZw+53X3pzQjsK/egJN7VVWnew5NNQ+J3qYU9qQ",
	"xl4vzg1ln0zvqqDymwwvoXrVw5tPqHaqSR6qrnfWOx1SbeR81ocuN7LdQtKqOHL7CQ1AX24kVFrjH0Dr",
	"mkqqofcAdgIbFtvHilBNlkwqTRZC6Ds6ex0+bz746PWZs5/fBk3xWWVd0fgYpipIyIbRVkUdSHL8/tQf",
	"l6dSmvGObu4lWFDzQ0AM+jad22kuRaMLyR1mwNWOaZq6E8eJ4L/XZQuhTZrOcOIO8VQsksAinhcrlE5I",
	"yF8uLt6XQ8C2tURajTAhz1qZ6mqLMK6/elELLOMaViBHIHXnQEqpYBL7mKxb+fduRrRW65aPOeyoaZM9",
	"Tv0xyWi8Zhx6u7peb1sd4EK7YOmlcdkLCZdRWWNOTt2ArAgwRSDLNdIACTY7ZDguXWaRbihLseMZOSYu",
	"xhCnVLpTMNyKsZusEeNFgfsLbJ5JbEBKlgBhPdnn3Ru5TCdVzCPvzAGBI3IZnduY7WVEhPRneu9ig6hm",
	"SnkydSzdGxcOQWc3cacmKgmohS6kowdEuDqcxG9rVIAKoLAl1kuRpuIat/63xQIkBw0KdTfxp0s+KFeL",
	"b2JwpkAxSVCROGhnLRLq+q7mRPt/ISlXNsLA+jKHTZxQj1VX75YpDsGrjYUj4UZ1H4Ae+ja0Kach1R5z",
	"7Qga2djm4hNThaEIXYhCuxFXwwuKtlgoVJTJn4FDX/Etzn5WelGzVdXSWqkmNyxw0u7cRJHbbn2b8G9f",
	"B21Cv3J5Ygo7nhLZjB1Wff5eDZrpsLDxbuHtiSRX2yQgS3eyac4HKaCKI5PyhNKFLGBCXtNUwYR84Fdc",
	"XDfCXPjchExThX9di4GuWWt0jlbr25J06+uqp76pVx5+MNSDTzwvrpRNK5Bqy/UaNIu9Kh1zJmpNNzAh",
	"jMdpYcBvypRJVCVkQyUTharMoUNZ5LjGGYgjkAARvD4B9kud0JiQcmC3QZ9IM14E9vRbukVogVuGLetS",
	"cPxMScoypomwZpIX2cIWahnnyIEySGzBjlMC5WU1xrYbBETWVJEMbY3hkGcpL6oCRGOY6U8FVDdyLcw4",
	"EtRfTCnzwAJQL5nXQlHIeaNKrOU28UAtcJiSwcZqTQ43tqoD/chyJDW7TyybTFURSrNiSiMuM7RwWA6I",
	"5UIphm86lrmZNp0ZnHe8pnxlixgNC/SackLJEq5JxniB7DJrmlOlENiVpyNwxcvr0pYMzJlWy2179qFQ",
	"FoyamhS7tI6VZfkkS9A4xTRtlnqW+WHjVklQueC4NQueglJkKwo7HgkxsIqVWlwBrw7vgpQ4HatLenBa",
	"Zg9enmrITkTBe1zQWqJUsVC4sFw74XLjNIy/XrN4bU6oIfvt9rEnAuuFLqfikBuU31phKW91SkhKF5Di",
	"cliuKkghRmBjzgC05byaRzkoRQqrN6qjcJZMyfQUlpoU3GwenhCRMY0+TFIYd0KBZDRlPzuM5g/U1Ral",
	"oIE8AWYkfQExLRS40iOcerwu+BVSEvVTwwKm3C13yjV6Ws9HgmOdlcD2nOxE0DH5+JmUro4wjq2R8c3z",
	"2fM/kkRUZVR1H67WimvguIyFgvqIRltucGZ/AKVZZvDFH+xuYz+7TEosUlw/M4gT40JVdwJivxKMpuyj",
	"rUWp+dCimw9wQ2M9CDDcDrWhXsq5swnqZzjRphWhaUpyVAHGDQ5aErsx3IZQ5g2nyowSd21tIXXAY0e3",
	"klaBMppY+0jT94Eoi18K3a7mdY0t7NpWCpE1ztt7XDKFmxadKE2zvCeGUyJd51sjsHM14cOhbAIpfExf",
	"bheY1w/pb7UDxR4Tq+LiSsU0Igues+AhXLczElCI9Qw+gBl5Xx2MK/m9VRqymclhTxEgDAS9Rh1+yvK/",
	"pbnR3zZgcgXbEs+kRQkFYsp9cy7kinLcwdgOEcNKSPz4RMUidweYjVZ+6gebOlLEh1VYLnoL5MU1D1Wn",
	"H/uRHaqJuOaqvJG0rFZmnFwaD3WOfV1GuwrHW9Y80CEvsY9jounWmu86tWM07O+Vd4OpQweNi1GHRGfR",
	"E4G4kExvz9HncCfogUqQx4Ve9zoozZfCjopHpk8fNnuyn16XkvrXv1+g12+6iI7c03pWa63zXsJCrk6T",
	"sEh8+HD6shIJK3+eA+mWuEZeM0Le0tw5z40XaiU9w6U3mQLsxFywGJVSGQm5+pEl9bhpzr4FkwqoBvnR",
	"LLYUbnEdGV+KEt3T2IAstHJpdBRpoNl/+3fH1oNDhtirXw3elSIlF0CzaBIVMnVMVkfzeePtzsY3IWhS",
	"BrOdvje+cZO2KTU053Jti4xyU3HnFWh6xq2qyLaF/bZIz+UJ/Hs53S0QKYuB23COm9xxTuM1kBezZ535",
	"XF9fz6h5PBNyNXfvqvmb05NX352/mr6YPZutdZaaDA7TpqKxxafmpI/fn3p1i0f1rb24zna1oqPoq9mz",
	"2XM0vlSvzVab05zNN8/tMXVboYpfr0D3lBX0Xd9UxftQokzTuqUyPbr7PpXJxHatkcW+1klChRHrGpEa",
	"+OtcjhJUWGPDpEXRqk/6zdNzR73czjRgTG4ndzoqgy57R2WeftyocMdk9IZlRdbwDpQ5SlcNyPdZKn+k",
	"j0foWTdGsTdtEeAWmg5rtL3LXbVw9706vG9HWeUdrCnpG1cVKDiIQejKmEhPhUUlWHwSvs+WuYJiT7JZ",
	"CdN388271bYxxMQebIyOlibWVA55IUQKlEe3tz8YU2xom+324tmzUnWC9U9pnqcuCT//pwsF1h0Mq2Mw",
	"9UpGN7eA/reoFL6+wz6rSGCnr29oQs6s42s7ff4AnX7gtNBrg+QS2+tXD9DrayEXLEnAZBK/fvGfD9Dl",
	"hRDkLeXbksUKu/7jg8z23JnQD7wKXVmAR1eqqm1ZVFUpuQil/k/sNRr9l7A1rYpt3khOu6DKNyLZ3sMO",
	"shOvg9uoV247e/f5vfUc4lYybt5737zPHmLzngi+TJl1IEd10VQXN9NSCyDo8LDp7SQEWee/oEW+tQrG",
	"VPYGjmSbeOZQVWObN1TNTgQ74ALICkUg+K5BhLu0pqlkdgGehwEPu4DDb0YNfP0AXX4nNHktCp6MeqCr",
	"B4J+6J9NHmDYPv4z6C9yE9+F1/IrcFFGLTNqmceKNuaxOR9mLs4LezfmOaFEFtwkOTu/kuOOhDNO3Em6",
	"CSl/BWFChCTuIJPNtJS5i9gdSwv4R+bJneo7c07ZkP31wJfRdfp1abMH9dbI1G5RV/7hNoep3DG7dNSv",
	"w/VrqUF3q9lUrHpTEggFU7FS5UGlEGIjr/FZrNmmvINjQpSWQDNl303ZxrUqy16SqqGNp7uayj8+e0ZS",
	"xkMJjwbOfCNWjwJqWi5YJrhYuyhUuiVPUnYF5KpYQKxT+3y6fBrk5BVAbt7mtvaFiBz4Pm7S1FE1afdU",
	"KOjPlJiS57vGrhpu9Bw2wPXUMqG5K1p5L7Eqb0eiytUXTc+Ba/JqY6t8LB+fmGo4O+D/Qg5bqfT59TSc",
	"FMfR5CllfPgwTHOCbzb7NTwxNWWBFQh1P+LvEX9/qfYBVX/bOLi7Ab1fr9yTrN5xPW1P0rrxxpi8HpPX",
	"95a8vndnqHvZ9OgYjQnhz6bzG8p7eGI4rMJ3JoibB5LvMVHcurj8MySMAyMYE8dj4vg3rVa6kLKFG3fD",
	"ysMTykNVlJdYbquowwMG/Z0+ikjtXsU1uqKjK/p59MfexPPQ/V4GBsfNPm72cbP/SsBCfWP3kABU38Xt",
	"PdGnlx7xMfQ0hp4ea+ip9bsLY9xpjDt9Np1fK+zhQaeA2t4ZcWpcindv4Sb/Nzw+Q6yp3f0YaBoDTb9d",
	"PdIFjj4y3IEaD48vDdJGXnCpoY0OdzZ7unsUnuZuHTW6maOb+RlUxd6A0qANXkaTxt097u5xdz9WIDC8",
	"dumAoqWxWmkMGT32kNFYpjSGi74E7X5ofdIhhUn3X5H0GUuRxhqkMTQ06owuGuxLJH50udEhdUafUHPw",
	"WIsNxiqD0UH8YtTB3tDP4CKicSePO3ncyY/PsH/kVRHuFwDtXRGOYuOyiPq3cD/xuoi7UyyP8MKI/Spm",
	"9FfGGyM+5cYIt0fGKyPuQNX2XRrR0riJuOapoElvkP2la9BGYVRqtqSxriOnElZMabkNOFmOxq8CnIlY",
	"Q/g6hCpEvWCcmqjxgEsEyJQcl6xcpGJBym5vJ9FXz150F8RsTzIlZ5AwCbH7vSTLekvhw9mbaBKtgSaG",
	"t79Eb0Rc/b5FPxtuTY//HriNH7JcSCq3dZ/31P1oQkZofHf6+iFk6bT8bQ973wl5JaWQj9FcVIZgj8E4",
	"+JqhttL2b8dxtAdcNFS1PPSmIZcr+8irhu7J4tzPXUMVjwZdNtTh6G/wtiHHg8923dCO/sc4zhjH+XKt",
	"hblxyPwqlfkVQaNO7S/3zCPc6Y5i57fzShWtiOC9v5HjlIx3+1FXYQYohYqAfFJuYoNo9Z1F8+l5tU2D",
	"aO64YMkn2zx3d/vD7f8HAAD//024Wg+9wQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../core/v1beta1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
