// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/core/v1beta1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x97XLcNrL2rWC5b5WlfSnq0z6xqlJ1tLKd1caOtZbs/bFKpTBkzwxWJMAA4EgTl+79",
	"VDcAfsyQ0iiWI3l3/iQaAgQajUb38zQA+nOUqqJUEqQ10eHnyKRTKDj9ecwtz9UE/yy1KkFbAVTAS/EJ",
	"tBFK4q8MTKpFaelndHR64stYBmMhwTA7BTZzzyBjrgOmxsxOhWEaSg0GpOXYAD7mkqnRvyG1CTsDjS8y",
	"M1VVnrFUyRloyzSkaiLFb3VrhllF3eTcgrFMSAta8pzNeF5BzLjMWMHnTAO2yyrZaoGqmIS9UxqYkGN1",
	"yKbWluZwe3sibHL5nUmE2k5VUVRS2Pl2qqTVYlRZpc12BjPIt42YbHGdToWF1FYatnkptkhYiYMySZH9",
	"WYNRlU7BJFEc2XkJ0WFkrBZyEt3E0aWQ2bIufxQyY8IwzlxNJ2ujMnyEo/7w+uychQ6cWp0Gm6qmUSYq",
	"QsgxaFdzrFVBrYDMSiWkpR9pLkBaZqpRISzO0q8VGIt6Ttgxl1JZNgJWlRm3kCXsRLJjXkB+zA18dVWi",
	"9swWqqxfmQVYnnHLUaH/T8M4Ooz+vN1Y+ba3me3Z7ggs3/1FlSB5KX55Tzp7B5ZjK6aE9K4W/Ao5w6r4",
	"iuW2Mqu+5Crf3MQRaldoyKLDf7XXljeL1oC8VD/Xg3bTjH37Vk8sFMuG1CpsmQSuNF6WuUjd2rNQlLiA",
	"nElwlrq3EnZiWanVTGRgcFHzKre4FsdiUmn3qltEzE65ZSmXaBtpZawqaIldTUEynmXBXjudKsbZOAew",
	"OJeP42ceaUU+CdtFm3D2+/CGeKStGPPU9syeZDwnH23FDBj3FdlY6YL3WILkBSy38p7+4DmbVgWXWxp4",
	"xkc5sEyYMudzhm9hk24CQifYOlzzosxR8H8cv//nHnslzCU7KfgE+ibFPVhZnWHY5/jaTRxVWvRoIAz5",
	"44cTtvH++IRpGIMGmULMPn54G7OzfVZyO40Z2DTZ7Er9a8Xn6Es1ZFNut/UU8q2RUjbd+jVVV3vLg1iY",
	"XBRpxck794Pvio9PaREtzBw7kWleoaNw4gjU6daoEnkGmqnKllWoaxL2yjkTCt8YDLiQoJkYMyXzOVMS",
	"upMmqwKFr2tGcRSGywsRxZEwCv+WPFUy41vu56zILvF/U7Rgza+iOJqk0Bq+11EcXW9hF1szrtFyDPY1",
	"oJDjlggDVf7hJRsoPiKBBwpPSPChN/3wbq30yQ16qJR0MVD4gVQ0UPgDaq5rKMfcwkTpuTMSmtDoMGr5",
	"+CheDkf0BhlQCDNMWCja02zmBoNZ3Gnq3rMW+joLrfWUHbU7WBhcCHOjvGcVHHeC4FhAnnWDIHpJMRaQ",
	"MW5pgCxHmMM2eB1JzSbBUzUDrUWWYaS0IYy52gnzjnjLveyD7bjKc4S0Zc5ToMa75RsI0grQE8g2lz2q",
	"i98UZbNMOD962qphdQXxrcMN3YCcfeLaxKxU2pqYzVReFWDiOv6ZPhf2OfLv4Z9v3//wy9vXn16/jQ4j",
	"xI3oiqg1nMyXOy93DvE/NDdLLssN5Izc8P2G8/ez9z8x96LDEBi909aEs5JrXoBF1IxzZKcgNI5bZKSC",
	"VgRv5MEo1BesXoHlIoeMZSqtigBEYlaS3+ejHFE5K7i+zNSVbEXCZU9+m9t+hfjC23KPDHUh4XPsgixX",
	"6YWFyJQORpiwU0IsaGQyw3VCMNC1hECLgOyyhRVgDAbUJSk++EDEfA0G12XOnfqvpnMXrUWnD9T+Fa4r",
	"q1immJDGAs+6MfGcXkPZO+8m7KMBJidCXm+VeWXaLy9Fer+acHpugRuEKwhYAmu90VXgRmtFYjhbiOCN",
	"QHcG66DIOwL2W2HsrdAfKzjwmuNfasxahebx4Pd/D81HkzDLynw7MB119RWBZ4NVI641n68zC08ks4AT",
	"7LjZ/UiWM4A71v2HwBv6PK0vCgun1KLget7AdoIewa+1KVnA6Mtewb/aY8dHw5QOcUIySWJGgD1mJ2fv",
	"KeoQS2DEEkzXQ/4rsL5bKFpA/8Sw7iRFN/Hn8KJjBne9hrVufr7/Oqx5b8967CWDp4vTgqTwStipqhos",
	"aPkkYWdVScCIdRijIcpoas7oEVcvZSy1KsBOoTKtPx+CMJ75pMNg/MEKnWjRzSEtg5Ae1NriGitORk1P",
	"buJAT+4zlx0CQE108NWKrbRRGTbiEhQ/9WY1/nZLMsNMERsKWasJI7mQk3531UGaH3XeF3nkJfoGuPaR",
	"tPNKb6NTVUDZi+vOp8BCKdqjT71AFxeVWg0m3UTahzWwKaUZ+kRaGB55dVrFN6m/oC4h2ceT3k58KlP3",
	"LUNXgr2V1SgXZoo/errbwOnmco41LfCCZmdzAFK23POK5tK49Js4MlOl7au2oEt+l420gDFTErZyIYG1",
	"ivvE75XTOM8ybCO+QkPraFLa9kITMAFL8GEKeZk8QDYtZNG8G+wLOzMucloroQ6rDIpwLGQqJAYkVqgM",
	"iTRSAY/YDUkbAiJkE4iZuRSlcelqY6nFdMqlhNyXEOAsIBPcNp0tRi3/CnFX10oUR2NuLDrQ0Hl0GO0l",
	"BwfJThRH1DbW3ksO9pMd8rN8Eh1Gs73k4DlVmQUcHvlHGMvaHYX2F9xTzcGiM0grLeycjcU1Lg7fdsJO",
	"c+AGAddE8wySFgvyQu6TBI1EB8sSHfRItDT0poX95Rbw0e8JtQE99UTamTBiJHJh7xMtPjUvLYZAar+9",
	"nls2eUdovD2H2vEsGPWFZAiNQ7BrJ8UUhuqx0MUV1yhBpsWMspDtpOgU8iKKMeJnOVgqLEplqD4Cy3sn",
	"0VDS92fR0pjeNIIslLwKci08H0icYtHfnNQLT/9RD2KppTCmxa5piN0JaPFYnufvx7RQfx8C+BwpCb6F",
	"jnnwCfbafZiJCaD1o2kvIJl6qSwhJl/iSFRAfyPIlZwQTWozwwHv2qyCB8IrNIzljMjxCXNl5ExFUVTO",
	"bdaLJGHvKlvxPJ8zuE7zyiA3QBt3cPYNkYNDZqZ87/mLwyTpYlb/mO9D9vJ5ymG0szcew4vv0ix7Oc6+",
	"OzjYefHiux0OL/ezF/v76Wj3xcHeXrazA9/x/0n39l4+fz46eJEd3JLpMf0wBsNHE0888ZVN7IibhGGb",
	"VnknStGkP8heivIDl33o6QyKGWimsRS9Qh3L6nxyaD0TGlKbzx2pc5K50IaT8NuWsRohiaPQFKWnyo7F",
	"NXRDVXRR7ezsw/e7yU6yw+hHupt4b98neF/orZOtv0veFSMtRpAt2hLqj7kRDSGKo91k18XP1dcHRaXF",
	"YRHNRAtFkcsqz4fN2Jl/V7FN3F7qfjaUUDuDgksr0trmRAbSirEAHajzbrKX7McYuXeSnS2d7m4mrM6l",
	"jpuELVM6A8rqILsPszDRvJx25RwScyHwzeoMRe20luPdz/ESKK3FWdzlYWOV5+oqrJ5FmIZmoRt8dSG5",
	"BiZVBmgWrGVYNCQaZBCMYdWcj/BPWrfK+FeTC/mxtTpdTUdGMzaaN6hww639zYAGN4oqt6KkJ0pfyHoJ",
	"sw3TWrKbra3PgeDR3iC6kH7Dp7NzE/hpwl5fc1oy6HQQwfMJoW3na4vK2M7uUnIho9sRyKcOGOrOVFNG",
	"m7Ba5YiBFa1hA+CsyEAvjQi4JNN8jEE60Kbs/iCjEeOVb6y38LTpoRnirbnvwbz3Ouf9ZHLe9853r3Pd",
	"/2257lvziz63iCWj3uxiOwgltdVRFKipk0sJ5CrFQL9VcMknkN2xSfYHpfJ+X2bsD0uK3SMf9qDprMfN",
	"ZD1EhmHQ2uuzpP32TsXtw5yklUprcjiutAO83FB7D4I4DN/XWas9WJzzpsGV/PainzgO/S578gXH0ZKw",
	"zz0MN7wy2x9s4q/cOM7f1dkqKczBNl1Csy+5tAKqrlsJXsuwjA6WON9FR+YQFtp6tpanUBh2dHrCPkCY",
	"wduUSBpYMgx8yup5wcBaUaBpIfsfqxFoCchAsbd29HHcD9kTTQ+dAc4yDNAO0KYM1cAQLC7ba86NPddc",
	"GqdMUQzsRGA9ZkUBIRh4WW39LrImDNuoNL9iUBKp7BQ0duy2LqPDCOPzFrbVHygHzrmQ92e19w+nXfwh",
	"GtRRmDo+UpX1Etfi9bocNTIIQLIfQIIeOOWDo09CZE0mdU3HzLvauOKGGbBsxA0gV3Td1gMX0r5opU8Q",
	"fE5A+2NOpt95b5D33mSuRrMJFPp8ZlYa6WqH6QftduB4vW817jOjelDxrUdu7upymdrX3rijhziQu3ON",
	"QP4Nzw3E7KO8lOpKtrkVlkdxRBWiOPI1ViVYXel8WwtPQ9MLj+uebhv1Hbnt2tJEG9y2RndUIvYARIPn",
	"p+8+gSZGG8Xtglcg3bM3dIRuuWqagjHC7Td0fgQnd8q1oapnc5nSH594LvD/H9BjVfZEnmo10WDQOD4i",
	"IncqRWAZqr7zmYD3VwgWSa6ZSOEVIBgXBqEtvrTaxLyWWuU5Io4Pjha0xrtU1h3uMXrDMZ3EOxMT7HO5",
	"icE6tS4Ha9RKHqzRFecDlMoIq/S8V/Wo8cGCpflpF9Zz9SYHsGEW6EffrLnZaM2de9CeQfdk1XnsMfua",
	"3fQSWixpsZDgg53jNXNpp2BF2sKdlMmZ8hnETFD2CKMCEgF34HTGtVCVqfEc+SCTsKOGpyIPxQaaI/Nq",
	"zD4310FiFgS76cV+VsiqZ/2+43PKMIFlwvmtyoCm35zlohDW5deAyaoYOUJAMJBpsJWWkLnURHNitA4+",
	"FMA0m3LDCqS4pCEe9nAThuHLUXRk4CX/tYI6yzEiOTKM08IYKqBoHah1SJa0WDhqnkKmQz6UArIKxdQC",
	"Zg4dSLi2NDZEzPVucq3uY6cmyqiiRzPCWMRU1BaK5Yl8qZyNB5X5kXaJKI47nXKJ1FJppwI75ZJxNoYr",
	"VghZobpoTktuDGROJWHGQwqKkom1tl0q3W170zjD1HpVXok8RxFdVjnledCU17Sby7HQhmhRqSQGo0rm",
	"YAybq8rJoyEFUavSqkuQ/rKYZKA1DscFzoGTEIU75esSo1XfGdvzjkWZamRwYqX1xuXlJMVfTUU6ZS43",
	"bP3ygcxVCRMdhpKwk3HzZjCWQPwzlzLG6XBaNZBDapU2Mb60aOf1OIJQhlUuUoZT4r6ZoPQcxpZVkhaP",
	"zJgqhLWQsayidJQBLXgufnNHbjqC0jwWZQ4W2AYIsvQRpLwywAQV49DTaSUvsSXVlIYz1DYgYaq02YxH",
	"g1eds8DFMbmBCPMlIwmpMkV3f8jGZ7vJ7nOWKZIbW2n6cFaOCFPiNOIg6iPWi3aDI/sLGCsKcvV/catN",
	"/Aae8qoc54+EOKYUXJ1nxX41kKccatuq4PkQudIPuPZXkO4ExjcrAMbWXb3lHdW6DMfYDSA8z1mJq9+g",
	"znuDiFsTImxE4Bvei5H/9nVTDdz2pAIoI8nrXED/TYqePbWlhJGv7JjFvPaFIoXeKxMkj0fhxvKi7PcL",
	"NZnzaVnkLm4o2epsLYMcfk9ffgHQ6/fpb3ILUTtizrultXfpJKVbfLhF4vyiyMDQvh/x+oSdqrLK6apE",
	"0Dfdd0rYB+AZ7Z2uyOvc5tkXTP87XpLrdrn2S5gHKLN0QzhEcqUnXOLipZ08d+gFf26YVJXuqXPIm3VI",
	"7rOi/juiFFBa9zVuufKrEA72zVJrU4Bbpq6kCRs87jmCN3ZBOe1t7OsiGr6+g2GwE8h7L8d62OOVSN3W",
	"+8GmhS2emdaGUGu79Zarzat4qFNu06nH+ihfneDrt4kxUdcFZ6IGVhbWqa9+l6BRU20+yDO6p+m2Y+mv",
	"Qs1oaYE/R7aUu+Z22jdtdL/rVJGC6Fh0fxIXDbNfVIeNfHZK6bBHnCxlFVQZeTH6EgZLB9MWtH1H3oC2",
	"rhzO8xKNlWYpz3O/nDIln9lQw8Hh1jpZ729+3f3NVGV9p3mqyQQoTv/t/Pw0TA7WbS6kO1YXsx3kCx4Q",
	"LXrp/b1eL73e6XzQnc6BBO7R0ocFljeiTCu5R3zVe7cB1z+UNC14OhUSBruq70U27lPUdOiC8mKVxsDj",
	"b2M6GiFMw6ShKO3cI38iDp0boC3+fYSYwSjJ0pxrF3C4dGbsB0tmPKrQ84CjIK3DLHckc29LjTbKY+8p",
	"kXHILqKzinJHFxF64NZIv7rZIPja4jLbai643n5Oqm+Du843k5tYKcOM6vKHtelysnPcI+Aa9FHlQp37",
	"9SY4ir//8xz7otrRoS9t5EXtEMDRk5OsP9R9/Hjyqp4Gh8daewYe8jRJiIS946XfLunUbzhLgkiIdgcl",
	"3T4CPY8CSENJfqGEXIiNpfgR5tENDp4ugPvklP94CJK0PDqMLPDif8e5mExtavNEqKZFHMQbKqF0jVY5",
	"Owde0C2v3OsALaTz9hJ4/Ve3iZ83+l7b9D7WMRq3wQ64WNzNN3dugC4Eq7H7tA1ZOGQTXNb4Tvs6+ZXS",
	"l7nimUku5IU8D7tzAc1tzHZ5Xk757maz40cP0Cwn0KKBjiNqQCdMztwqn2hyx8NykYJ0m3leZ0clT6fA",
	"9ugMYFdNV1dXCafiROnJtn/XbL89OX7909nrrb1kJ5naIid8IywdJ1xQ/9HpSeeUfxgIWaKDPtFhtJ/s",
	"JLsePZGhb/v9ZfoxATtwdMjvg7NOcK4dCJo51QsHPaiHcJmf9oN7MLc/yVpXRA2S4YYciaGPldQR0GHw",
	"dsbSryBqARsgul0gmm4l23ylZyFF98wnWbw3LzXMKOvbzWANrKQ6hevXP++haDdxH/N0KS6XC8WaqW0S",
	"T5Tl8pnFkEBwxFJof76y+/UWmIGe26mQkyFB6a0z3+sfKK07dBmHQx+UJyMzURpVfAns2ffPYvbse/wv",
	"Lstnf/r+WThyexFdwnz3e5q33fgS5nt/cj/2LqLNoZFSj79vpGhJBb8WRVV0Eo7O8OpBttOgTYrzvEk5",
	"U7rC5deGDa3zOmLQjpXDtTDWNbqQS0ZASGnE7gdOTGvhCIkOssnekoYGLUMUwnb0dCcCvqGrVE5ychR7",
	"OzshZvhvN7S+GrP9b4+6mh5WOKxDZ0opIi2k6H5ED3bwgB0OEMKevv/KMxZ4OQmx+whCfJS8slPK0WRO",
	"iv1HkOKN0iP6Xg6JsPfyEUQ4V4q943IepsSgKM8fRRtnHox8lDWSd6kePqHdZh9UaU+zVL2HpSmTyvhS",
	"ZF0OrK5qOIjrQDAY+1eVzR96EbqxNijb6gpultb+7tfptk9B2XrxP7nFv/MYi/9YyXEuXIZv7X7u4X6u",
	"t4JnQfga8PlN3CD/7c/+r5vtOvN8JxOg89nh06XHzfHgQU5AL9zFCxa3D/qcI2Eayv42qLzjGxvXdT/Y",
	"+wWc5MmxhYdnBV+Clb8tJFp/3WuNRr+RgHTwCCL8pCx7oyqZrSPSVwHE9PVsIraD0aUDjE/c90afSnj5",
	"+avidPf5uR6LaAblvz4edp1U6xjKH47vh8RdY/y1Sx10qY9OM75RbO9B/G0If/szerYb54RzsL3fz6Vj",
	"kF13fBfcdy89TYccr9h3x28O9E//u3c0+Pqo9TbEuvZsT8WzPX2/0sv+f6DLCPdxBz+AXfuCtS9Y+4Jv",
	"2ReUle370rH7ZxDuw9b8O2uP8A1wxfro7d1k8Q92Xmt2uvbba3b6H8ZO781Gb9kt73DQL40w9A+gUIPf",
	"AvpbfRrXQHC9g/AN7yDczU9vcRANK30I7zBxl0i+EWK49gVrX/CftpvIbdpzH5HuVK7kD6jmA3oEEuhR",
	"qOEWdf3/v2xWOpdRVzoO+Id6qTUPW7vKJ8XD1s76S5OJ9Amp1chdN4f4EN7a3ZH9NjJ5T84dr4+CrwPA",
	"OgCsA8DDnkanbOB2c4d9kO23v7t8H95/Fm6Jf43dpzXtX7uyNe1/XNp/P8fQTgA8QdewZv9r9r/2mGuP",
	"+TW59/0cZpeFf8Mu89tn4GtvtKaiayr6kFSUvgdGn+IjL+a+07TNS7E926V/Ica3tfQp4eAi6Z9C7P1e",
	"0sL5xJufb/4vAAD//0pPS/YPlgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../v1beta1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
